version: '3.7'

services:
  node:
    container_name: node
    hostname: node
    restart: unless-stopped
    user: '${CURRENT_USER_ID}:${CURRENT_USER_ID}'
    build: 
      ./node
    environment:
      - PORT=${PORT}
    working_dir: "/home/node/app"
    volumes: 
      - "../www:/home/node/app"
    links:
      - mongo-db

  mongo-db:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
